# Site settings
title:       Tdd Apps
email:       support@tddapps.com
author:      Tdd Apps
company_name: TDDAPPS LLC
description: >
  Ideas about sofware craftmanship and automation.
  Things that were hard to discover.
  Useful tips about some tools.
  And book reviews.
opinions: >
  The opinions on this website do no represent those from my employers or clients.
baseurl:     ""
url:         "https://www.tddapps.com"

keywords:
  - code
  - software
  - craftmanship
  - engineering
  - tdd
  - agile
  - docker
  - virtualization
  - logs

# Google analytics
google_analytics: UA-66099838-1
optimizely_experiment: 0000000000
hotjar_id: 00000

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true
show_social_icons:  true

# Social icons
github_username: tddapps
twitter_username: tddapps

# Post sharing icons
show_sharing_icons: false
share_text: 'Was this post helpful? Share it with the world.'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true
show_email_signup: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
plugins:
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate

github: [metadata]
kramdown:
   input: GFM
   hard_wrap: false


defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: page-bootstrap
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post-bootstrap
