# Site settings
title: Tdd Apps Blog
description: >
  ideas about many things
baseurl: ""
url: "http://tddapps.com"
twitter_username: tddapps
github_username: tddapps

# Build settings
markdown: kramdown
